environment:
    ooebv-username: EGGER5
    ooebv-password:
        secure: fohNC7EhImjczRjtEvJx4Q==
    facebook-access-token:
        secure: 66WgMSI23Zp+cbm/mcTtBUK641HsnWs8yUr1vt6U9l20eT3czK+Zm7J2ZC5VuLfo9GllOtS7EbVRHENZphl7RrSiOKnXJ1ZC6+nenPOo+x3snPKhVvmytUJQGPmPtDL2Z5EYAOU46hCEsGupJ2gwUkvrhFkBOWZrwEgmNc0cEcB9rh89ZEsbbPWyTlrvQzXpKMEuy6liv550fzrCxm4ThuAA4datow0OgbVvbSfRE1E=
    upload-url: ftp://s1.meinehp.at/web/a/
    temp-url: ftp://s1.meinehp.at/tmp/upload/
    upload-username: wk-laufenatftp
    upload-password:
        secure: w4rIlEoHl+x1gtgnZvCHzw==
    mail-host: s1.meinehp.at
    mail-port: 587
    mail-username: web@wk-laufen.at
    mail-password:
        secure: Hx38EcvsQtvuXz09Mu4i5A==

install:
    - cmd: .paket\paket.bootstrapper.exe
    - cmd: .paket\paket.exe install

build_script:
    - cmd: packages\FAKE\tools\FAKE.exe Scripts\Build\run.fsx

test: off

artifacts:
  - path: WkLaufen.Website\bin\html\**\*.*

deploy: off

notifications:
    - provider: Email
      to:
        - j.egger@posteo.at
      on_build_success: false
