environment:
  ooebv-username: EGGER5
  ooebv-password:
    secure: fohNC7EhImjczRjtEvJx4Q==
  facebook-access-token:
    secure: 0nOYEDZXK8LoT5QCvfS311U/tsooJZ+3Qi8nxvzWRS1Gn2gis56zkpS2lijZhwa4MaZ5SV85x+vFJl9i43AJ0HlTxLOeyv79+TobrXBj/S35Lm8cPI/METzAMLzqOS8isVf2Th6Tcb8LGAlVCL4v4Grb6FFNxWfhU8K+EoChIz5hW2bwl6nqx+YZRwTNzuGIYShL7xkdOXrcXdydTkE6UHAL+2RJrodJcdPG6UBC6sZDUQA/os2wayzWsUm0UCQh
  public-calendar-url:
    secure: pzv+VBoHIjy4e3yFDxI3sXeV2gOYJwqQigDPKScRiDcX3A0s7ItaulrNPh/LlPzng64oZCI0OOIk/N2WcBQCUCURZRcZ/4LLIp3fTVo01aEp9gzmXaZEvbCLKAsC8pztHZ4WunfOr1kjEuQBiQ+FYaWW9O4qIRkwCw1/LFa4qSrXfiln5K/Ld3QYbileBoSYQ3QK8rQgrrOoyePvkjvJzQ==
  internal-calendar-url:
    secure: pzv+VBoHIjy4e3yFDxI3sXeV2gOYJwqQigDPKScRiDexfJlT+o29OMmwtN7sqh0a68lD/FEhnfSsgkibDZ/cehqa98m7d8j+vU29TDgHz55PP2neKXv1epnDSjDjcGoHcV9nbDh6yyJWdeY3LYPLHIZTpI7bCml/BJAyRy4E855oCs9Oumuz2YwA5hgWDOyWwrhL3Mb6ObKdTJ//VKw0HA==
  upload-url: ftp://s1.meinehp.at/web/a/
  temp-url: ftp://s1.meinehp.at/tmp/upload/
  upload-username: wk-laufenatftp
  upload-password:
    secure: w4rIlEoHl+x1gtgnZvCHzw==
  mail-host: s1.meinehp.at
  mail-port: 587
  mail-username: web@wk-laufen.at
  mail-password:
    secure: Hx38EcvsQtvuXz09Mu4i5A==

init:
  - cmd: dotnet --version
  - cmd: yarn -v

install:
  - cmd: dotnet restore
  - cmd: yarn
  - ps: .\load-data.ps1

build_script:
  - ps: .\build.ps1

test: off

after_build:
  - cmd: 7z a app.zip %APPVEYOR_BUILD_FOLDER%\public\.
  - ps: Push-AppveyorArtifact app.zip -DeploymentName app
  - ps: Push-AppveyorArtifact src\publish.php -FileName publish.php -DeploymentName publish-script

deploy:
  - provider: FTP
    protocol: ftp
    host: s1.meinehp.at
    username: wk-laufenatftp
    password:
        secure: w4rIlEoHl+x1gtgnZvCHzw==
    folder: /tmp/deploy
    artifact: app

  - provider: FTP
    protocol: ftp
    host: s1.meinehp.at
    username: wk-laufenatftp
    password:
        secure: w4rIlEoHl+x1gtgnZvCHzw==
    folder: /web
    artifact: publish-script

after_deploy:
  - ps: Invoke-WebRequest -Uri "http://wk-laufen.at/publish.php?package-name=app.zip" | Out-Null

notifications:
  - provider: Email
    to:
    - j.egger@posteo.at
    on_build_success: false
