environment:
    ooebv-username: EGGER5
    ooebv-password:
        secure: fohNC7EhImjczRjtEvJx4Q==
    facebook-access-token:
        secure: lQXtk7jvh5pcal+K/ms7mg3u6v+eWSaY7m5dAEUdbjkZUSZxgNh3MsRIPJdxUB/P+kToJjjLn4xD5bGdT6aWbBxrukD5rAvKPDKt/Pi0zvYW/cSUe5g2BNgILrwa4wd5zUWIyAH679OE9xn9TowHRYQuHlEBYhb0CMZyOvSKRw8Hl/wgvsDcWpYqisJEBY3cpw2mAWQDiTsVVH13+YtB2BrTSUeUMwwVOuzKgPNmG5RFxhAOBW+jbcAjry8g5+vw
    upload-url: ftp://s1.meinehp.at/web/a/
    temp-url: ftp://s1.meinehp.at/tmp/upload/
    upload-username: wk-laufenatftp
    upload-password:
        secure: w4rIlEoHl+x1gtgnZvCHzw==
    mail-host: s1.meinehp.at
    mail-port: 587
    mail-username: web@wk-laufen.at
    mail-password:
        secure: Hx38EcvsQtvuXz09Mu4i5A==

install:
    - cmd: .paket\paket.bootstrapper.exe
    - cmd: .paket\paket.exe restore

build_script:
    - cmd: packages\FAKE\tools\FAKE.exe Scripts\Build\run.fsx

test: off

artifacts:
  - path: WkLaufen.Website\bin\html\**\*.*

deploy: off

notifications:
    - provider: Email
      to:
        - j.egger@posteo.at
      on_build_success: false
